<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.wis</groupId>
        <artifactId>CoreParent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>User-Service</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.wis</groupId>
            <artifactId>Common</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.3.2</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>${project.basedir}/src/main/java/com/wis/i18n</directory>
                            <includes>
                                <include>Translate.java</include>
                                <include>KeyTranslate.java</include>
                            </includes>
                        </fileset>
                        <fileset>
                            <directory>${project.basedir}/src/main/java/com/wis/i18n/exception</directory>
                            <includes>
                                <include>TranslateException.java</include>
                            </includes>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>generate-translate-enum</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>python</executable>
                            <arguments>
                                <argument>${project.basedir}/src/main/resources/generate_translate_enum.py</argument>
                            </arguments>
                            <environmentVariables>
                                <PYTHONIOENCODING>utf-8</PYTHONIOENCODING>
                            </environmentVariables>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-translate-exception</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>python</executable>
                            <arguments>
                                <argument>${project.basedir}/src/main/resources/generate_translate_exceptions.py</argument>
                            </arguments>
                            <environmentVariables>
                                <PYTHONIOENCODING>utf-8</PYTHONIOENCODING>
                            </environmentVariables>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <release>${java.version}</release>
                    <parameters>true</parameters>
                </configuration>
            </plugin>

        </plugins>
    </build>
</project>
